theme: minimal-mistakes-jekyll


title: "Yifei Zhang"
subtitle: "Data-centric Security ML"
description: >-
  Network telemetry, anomaly detection, model failure analysis, and drift-aware security analytics.

url: "https://Zyffff999.github.io"
baseurl: ""
repository: "Zyffff999/Zyffff999.github.io"

github_username: "Zyffff999"
minimal_mistakes_skin: "dark"
search: true
locale: "en-CA"
timezone: "America/Montreal"

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"

# Outputting
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name: "Yifei Zhang"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "Data-centric Security ML | Network Telemetry | Anomaly Detection | Drift-aware Detection"
  location: "Ottawa, Canada"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Zyffff999/"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "yifeizhang7@cmail.carleton.ca"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
      toc: true
      toc_sticky: true
      show_date: true

  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/
